### ISSUE TITLE
Unable to use "Open with GNOME MPV" from file browser due to "loading failed"

### ISSUE THREAD

**Issue by ahayzen** [flathub/io.github.GnomeMpv#1]
What happened;
1) Install the GNOME MPV flatpak and have a video file ready
2) Open a file browser (eg Nautilus)
3) Right click on the video and select Open with GNOME MPV
4) Notice how GNOME MPV starts, correctly, but then a dialog appears stating "Error. Playback was terminated abnormally. Reason: loading failed."

What I expected to happen:
At step #4 to be able to play the video successfully.

Note that if you open GNOME MPV directly and use "Open" from within the application it is able to open the same file successfully.

```
$ flatpak --version
Flatpak 0.10.0
$ lsb_release -rd
Description:	Ubuntu 17.04
Release:	17.04
$ flatpak run io.github.GnomeMpv --version
GNOME MPV 0.13
```

I've not been able to locate any useful logs yet, journalctl only shows the following:
```
<time> <device> dbus-daemon[1500]: Activating service name='io.github.GnomeMpv'
<time> <device> systemd[1481]: Started flatpak-io.github.GnomeMpv-4012.scope.
<time> <device> dbus-daemon[1500]: Successfully activated service 'io.github.GnomeMpv'
```

**Comment by TingPing** [comment]
Do you have `xdg-desktop-portal-gtk` installed?

**Comment by ahayzen** [comment]
@TingPing Yes I do.

```
$ apt-cache policy xdg-desktop-portal-gtk
xdg-desktop-portal-gtk:
  Installed: 0.7-0alexlarsson2~zesty
  Candidate: 0.7-0alexlarsson2~zesty
  Version table:
 *** 0.7-0alexlarsson2~zesty 500
        500 http://ppa.launchpad.net/alexlarsson/flatpak/ubuntu zesty/main amd64 Packages
        100 /var/lib/dpkg/status
     0.6-1 500
        500 http://gb.archive.ubuntu.com/ubuntu zesty/universe amd64 Packages
```

**Comment by ahayzen** [comment]
This is now working correctly in Artful (Ubuntu 17.10), therefore I will mark this issue as closed.

```
$ apt-cache policy xdg-desktop-portal-gtk 
xdg-desktop-portal-gtk:
  Installed: 0.7-2
  Candidate: 0.7-2
  Version table:
 *** 0.7-2 500
        500 http://gb.archive.ubuntu.com/ubuntu artful/universe amd64 Packages
        100 /var/lib/dpkg/status
```
