### ISSUE TITLE
Can't write PNG screenshots

### ISSUE THREAD

**Issue by FakeShemp** [flathub/io.github.GnomeMpv#10]
If I add `screenshot-format=png` to a config file, taking screenshots will no longer work. The result is zero-byte files unfortunately.

**Comment by TingPing** [comment]
Hmm, libpng is certainly in the runtime, ffmpeg has basically everything enabled, no useful guess off hand.

**Comment by TingPing** [comment]
This probably does it, let me know next update: https://github.com/flathub/io.github.GnomeMpv/commit/c20f423f9f322e29086ebe867384e86008403527

**Comment by FakeShemp** [comment]
Works beautifully <3
Thank you very much!
