### ISSUE TITLE
Assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

### ISSUE THREAD

**Issue by deikatsuo** [flathub/io.github.GnomeMpv#2]
![screenshot from 2018-01-17 07-38-39](https://user-images.githubusercontent.com/8337409/35019491-c5ec0e10-fb59-11e7-827e-23271effb6d0.png)

Flatpak 0.10.2.1

**Comment by TingPing** [comment]
Fixed by 8e82a47fdeafa6133c3451387af32cd7cf81ea8c

Building now: https://flathub.org/builds/#/builders/1/builds/1615
