### ISSUE TITLE
it should pull org.freedesktop.Platform.GL.nvidia

### ISSUE THREAD

**Issue by alex285** [flathub/io.github.GnomeMpv#4]
i installed GNOME MPV
```
flatpak install flathub io.github.GnomeMpv`
```
but when i tried to launched it i got
```
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
```
it was a clean Fedora 28 installation and GNOME MPV was the first application i installed, and i didnt notice (actually i used GS, thats why) i was missing the NVIDIA runtime, that i had manually to install

```
flatpak install flathub org.freedesktop.Platform.GL.nvidia-390-42
```

**Comment by alex285** [comment]
actually that should be a Flatpak bug, rather MPV. if yes, please tell me to move it on Flatpak

**Comment by TingPing** [comment]
What version of `flatpak`?

**Comment by alex285** [comment]
@TingPing oops sorry!
Flatpak 0.11.3 on Fedora Rawhide

**Comment by TingPing** [comment]
Odd, it always should and does pull it in here.

**Comment by alex285** [comment]
@TingPing if you tested that and it works, then i will close this, because it is impossible to uninstall everything and re-try! if i get time (that i doubt), i will make a Fedora installation on KVM and check on that

**question:** Flatpak pulls NVIDIA runtime only when you have NVIDIA drivers installed? perhaps when i pulled GNOME MPV, i hadn't NVIDIA drivers, and install them later? can be such case?

**Comment by TingPing** [comment]
> @TingPing if you tested that and it works, then i will close this, because it is impossible to uninstall everything and re-try!

Sure you can:

```
> flatpak --gl-drivers
nvidia-390-42
default
host

> flatpak uninstall --user org.freedesktop.Platform.GL.nvidia-390-42/x86_64/1.4 io.github.GnomeMpv
Uninstalling: org.freedesktop.Platform.GL.nvidia-390-42/x86_64/1.4
Uninstalling: io.github.GnomeMpv/x86_64/stable
Uninstalling: io.github.GnomeMpv.Locale/x86_64/stable

> flatpak install --user flathub io.github.GnomeMpv
Installing for user: org.freedesktop.Platform.GL.nvidia-390-42/x86_64/1.4 from flathub
[####################] Downloading: 47.1 MB/47.1 MB (3.1 MB/s)                 
Installing for user: io.github.GnomeMpv/x86_64/stable from flathub
[####################] 1 delta parts, 6 loose fetched; 9635 KiB transferred in 4 seconds
Installing for user: io.github.GnomeMpv.Locale/x86_64/stable from flathub
[####################] 3 metadata, 1 content objects fetched; 2 KiB transferred in 1 seconds
```

**Comment by TingPing** [comment]
> question: Flatpak pulls NVIDIA runtime only when you have NVIDIA drivers installed? perhaps when i pulled GNOME MPV, i hadn't NVIDIA drivers, and install them later? can be such case?

Correct. `flatpak update` also pulls in drivers if needed.

**Comment by alex285** [comment]
@TingPing  yeap it worked fine. i even tried from GNOME Software to see if there was something wrong on this part! but everything okay
