### ISSUE TITLE
Please consider building with vaapi hardware decoding support.

### ISSUE THREAD

**Issue by Enaunimes** [flathub/io.github.GnomeMpv#5]
VAAPI extension has been available for a while for flatpak, and VLC has been utilizing it. Please consider switching it on for MPV, too.

**Comment by TingPing** [comment]
It should already work fine, can you expand on what problems you are finding?

**Comment by Enaunimes** [comment]
I'm using Fedora 28 Workstation.
While running gnome-mpv from the shell spawned by flatpak run  --command=/bin/bash 
io.github.GnomeMpv, it yields this error message:
```
libva info: VA-API version 0.39.4
libva info: va_getDriverName() returns 0
libva info: Trying to open /usr/lib/dri/emgd_drv_video.so
libva info: va_openDriver() returns -1
```

After specifying LIBVA_DRIVER_NAME=i965 from the commandline, the error message became:
```
libva info: VA-API version 0.39.4
libva info: va_getDriverName() returns 0
libva info: User requested driver 'i965'
libva info: Trying to open /usr/lib/dri/i965_drv_video.so
libva info: Found init function __vaDriverInit_0_39
libva error: /usr/lib/dri/i965_drv_video.so init failed
libva info: va_openDriver() returns -1
```

**Comment by Enaunimes** [comment]
https://github.com/mpv-player/mpv/blob/4d1269d9dbbd839d1f14f40a03918c96641715c2/wscript#L675 requires libva to be present while buidling, but I didn't find it in io.github.GnomeMpv.json.

**Comment by TingPing** [comment]
Yea it is there:
```
> flatpak run --command=pkg-config org.gnome.Sdk//3.28 --modversion libva
0.39.4
```

**Comment by Enaunimes** [comment]
Thanks, I didn't know that.
Do you know the reason for the error message above?

**Comment by TingPing** [comment]
Some incompat with the host drivers maybe? It works completely fine on my Intel hardware.

**Comment by jonubulin** [comment]
I have the same issue with Intel Hardware on Fedora Silverblue 29

**Comment by qnixsynapse** [comment]
I really find it weird but vaapi on amdgpu suddenly stopped working. It used to work before. Was there any recent changes on the freedesktop runtime?

**Comment by paulcarroty** [comment]
works fine.

**Comment by qnixsynapse** [comment]
@paulcarroty I can confirm that gnome-mpv flatpak isn't working on any of the machines running arch linux and Fedora. :(

**Comment by paulcarroty** [comment]
Tested on Clear Linux with Intel GPU, vaapi works.

**Comment by qnixsynapse** [comment]
@paulcarroty  Not intel , amdgpu. Intel GPU has separate runtime for the driver that I know. It's appears to be a new regression.

**Comment by Erick555** [comment]
@akarshanbiswas vaapi driver was intentionally disabled for amd cards: https://gitlab.com/freedesktop-sdk/freedesktop-sdk/issues/798

@TingPing this issue isn't related to GnomeMpv app so it can be closed.

**Comment by qnixsynapse** [comment]
@Erick555 Wait a sec, They removed the whole driver from the runtime because of gst-vaapi?

a huge facepalm!

But anyways. I going to rant there. This issue can be closed.

**Comment by paulcarroty** [comment]
https://gitlab.freedesktop.org/gstreamer/gstreamer-vaapi/issues/100 seems like it's resolved now.

**Comment by qnixsynapse** [comment]
@paulcarroty   https://gitlab.freedesktop.org/gstreamer/gstreamer-vaapi/issues/137#note_172155
