### ISSUE TITLE
Taking a screenshot creates file in sandbox and is summarily deleted on exit

### ISSUE THREAD

**Issue by mystise** [flathub/io.github.GnomeMpv#6]
When taking a screenshot it shows the proper notice at the top of the screen "Screenshot gnome-mpv-shot<number>.jpg" and the number properly increments, but the screenshot itself doesn't seem to be written anywhere.

Even inside the sandbox (flatpak run --command=/bin/bash io.github.GnomeMpv), no files are created and no relevant log messages are output if I run gnome-mpv from bash.

Edit:
I didn't notice before but running gnome-mpv from bash inside the sandbox produces the output files in ~ inside the sandbox, but they're deleted as soon as bash exits.

**Comment by TingPing** [comment]
Some options:

- GNOME-MPV creates a filechooser to select the location
- GNOME-MPV defaults it to a location like xdg-pictures and we can grant write access there

**Comment by TingPing** [comment]
But in the end this needs to be reported upstream: https://github.com/gnome-mpv/gnome-mpv
